[package]
name = "nash"
version = "0.1.0"
authors = ["Zekai.Zheng <kiddkai@gmail.com>"]

[dependencies]
nix = "0.7.0"
libc = "0.2"
rusoto = {version = "0.15.2", features = ["s3"]}
hyper = "0.8.1"
docopt = "0.6.85"
rustc-serialize = "0.3.19"
